services:
  apachephp:
    container_name: ${projectname}_apachephp
    build:
      context: ${buildcontext}
      args:
        uid: ${UID}
      dockerfile: ${dockerfile}
    environment:
      - APACHE_RUN_USER=#${UID}
      - APACHE_RUN_GROUP=#${GID}
      - APP_URL=${url}
    working_dir: /var/www/html
    ports:
      - ${extport}:${innerport}
    volumes:
      - ../moodlesrc:/var/www/html
      - ../moodlelogs:/var/log
      - ../moodledata:/var/www/moodledata
    networks:
      - projectnetwork
  mysql:
    container_name: ${projectname}_mysql
    build:
      context: ./db
      dockerfile: mysql/mysql.dev.dockerfile
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - "${MYSQL_OUTPORT}:3306"
    volumes:
      - ../mysql_data:/var/lib/mysql
      - ../mysql_logs:/var/log/mysql
    #command: --default-authentication-plugin=mysql_native_password
    networks:
      - projectnetwork
networks:
  projectnetwork:
    driver: bridge
